// @ts-check

const path = require("path");
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "react-composable-form": [
    { type: "autogenerated", dirName: "react-composable-form" },
  ],
  "react-imperative-hook": [
    { type: "autogenerated", dirName: "react-imperative-hook" },
  ],
};

module.exports = sidebars;
