const projects = [
  defineProjectByConvention("react-composable-form", {
    description:
      "Form library for React with focus on composition, convention and type safety.",
    imageUrl: "/img/jigsaw.png",
  }),
  defineProjectByConvention("react-imperative-hook", {
    description:
      "React hook for improved DX with async UI flows like modals, toasts, drawers, etc.",
    imageUrl: "/img/steps.png",
  }),
];

function defineProjectByConvention(
  packageName,
  { imageUrl, description } = {},
) {
  return {
    packageName,
    title: packageName,
    href: `/docs/${packageName}/`,
    imageUrl,
    description,
    sidebar: [packageName, [{ type: "autogenerated", dirName: packageName }]],
  };
}

module.exports = { projects };
