name: Build and Test
on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm depcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: npx playwright install --with-deps
      - run: pnpm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright
          path: "**/.playwright/**"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm build
        env:
          # We can only build for development in CI,
          # since production settings and builds are handled externally (e.g. by Vercel).
          # This CI job is only for sanity testing the build process in the CI.
          NODE_ENV: development
