name: Build, Test and Release
on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm depcheck

  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy # Has to be same version as in package.json
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm test
        env:
          HOME: /root # Workaround required when using playwright image in ghactions. See https://github.com/microsoft/playwright/issues/6500#issuecomment-845919578
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright
          path: "**/.playwright/**"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm build
        env:
          # We can only build for development in CI,
          # since production settings and builds are handled externally (e.g. by Vercel).
          # This CI job is only for sanity testing the build process in the CI.
          NODE_ENV: development

  release:
    permissions:
      contents: write
    needs: [conventions, test, typecheck, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - name: Setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # The release command may have updated package.json versions, which we want to commit and push.
      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --exit-code || exit 0  # Exit if there are no changes
          git commit -m "chore: release"
          git push
