name: Build and Test
on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm depcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: npx playwright install --with-deps
      - run: pnpm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright
          path: |
            **/.playwright/**
            !node_modules/**

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composites/install/
      - run: pnpm build
        env:
          NODE_ENV: production
          # No additional application specific environment variables should be provided here or in the CI.
          # Application environment variables should be provided by the external deployment build system.
          # (Providing no environment variables here also ensures that all apps support being built with zero config)
      - run: pnpm typecheck
