name: Conventional Commits
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/composites/install/

      - name: Lint all commits in push event
        if: github.event_name == 'push'
        run: pnpm exec commitlint --from ${{ github.event.before }} --to HEAD --verbose

      - name: Lint all commits in pull request
        if: github.event_name == 'pull_request'
        run: pnpm exec commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
